### ISSUE TITLE
running the container without root permission

### ISSUE THREAD

**Issue by oupala** [codimd/container#93]
We're trying to run the container without root permission. It does not work and we get the following error in the log:

```
/usr/local/bin/docker-entrypoint.sh: 80: exec: app.js: not found
```

We can make it work by overriding the entrypoint, but we do not have features such as db migration.

Why is there so many rights management in the entrypoint? The rights management should be embedded in the Dockerfile. This would make the startup of the container faster.

We should maybe work together on `Dockerfile` and `docker-entrypoint.sh` optimisations.

**Comment by SISheogorath** [comment]
There is not much happening in the entrypoint. It sets some permissions on directories if they are volumes or print a warning and that's it. Means: this permission management can't be done in the Dockerfile.

The rest of the entry point script is just setting some variables, wait for the database and running the migration script before starting codimd itself as non-root user.

But I'm not sure why your start fails what do you pass as "command"?

**Comment by oupala** [comment]
It is possible to manage permissions in Dockerfile. But I think the point of the `docker-entrypoint.sh` is to manage persmission for mounted volumes, which can't be done on build time as volume are not yet available. I can now see the point.

Let's concentrate on why the start fails. I do not pass any `command`. I'm using a yaml template to deploy on a k8s cluster.

```yaml
# ==================================================
# codimd k8s template
# ==================================================
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: codimd
  labels:    
    app: codimd
objects:

# codimd app Deployment 
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations: {}      
    creationTimestamp: null
    labels:
      app: codimd
      service: app
    name: codimd
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: app
      spec:
        containers:
        - name: app
          args:
            - app.js
          env:
            - name: DEBUG
              value: 'true'
            - name: CMD_LOGLEVEL
              value: 'DEBUG'
            - name: CMD_DB_URL
              value: mysql://hackmd:hackmdpass@myq-codimd-maria-db-dev-service-sql:3306/hackmd
            - name: CMD_ALLOW_GRAVATAR
              value: 'false'
            - name: CMD_ALLOW_PDF_EXPORT
              value: 'false'
            - name: CMD_DEFAULT_PERMISSION
              value: 'limited'
            # enable TLS for OIDC callback
            - name: CMD_PROTOCOL_USESSL
              value: 'true'
            - name: CMD_DOMAIN
              value: 'codimd.example.org'
            - name: CMD_URL_ADDPORT
              value: '443'
            # anonymous use forbidden
            - name: CMD_ALLOW_ANONYMOUS
              value: 'false'
            # no account creation using email
            - name: CMD_EMAIL
              value : 'false'
          image: codimd/server:1.6.0
          ports:
          - containerPort: 3000
          resources: {}
        restartPolicy: Always
  status: {}

# codimd app Service
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: codimd
      service: app
    name: codimd
  spec:
    ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    selector:
      service: app   
  status:
    loadBalancer: {}

# codimd app Route
- apiVersion: v1
  kind: Route
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: codimd
      service: app
    name: codimd
  spec:
    host: ""
    port:
      targetPort: "3000"
    tls:
      termination: edge
    to:
      kind: Service
      name: codimd
      weight: 100
    wildcardPolicy: None
```

I made a mistake on my previous deployment, in fact it seems to work. Stay tuned, I have some things to check and I'll come back here.
